# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:/random_dice/mymodify/_guifiles/frame_test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 800)
        self.land_09 = QtWidgets.QGraphicsView(Dialog)
        self.land_09.setGeometry(QtCore.QRect(100, 60, 100, 100))
        self.land_09.setObjectName("land_09")
        self.btn1 = QtWidgets.QPushButton(Dialog)
        self.btn1.setGeometry(QtCore.QRect(300, 200, 80, 40))
        self.btn1.setObjectName("btn1")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(300, 320, 200, 90))
        self.textEdit.setObjectName("textEdit")
        self.player2_text = QtWidgets.QTextBrowser(Dialog)
        self.player2_text.setGeometry(QtCore.QRect(550, 650, 250, 150))
        self.player2_text.setObjectName("player2_text")
        self.land_10 = QtWidgets.QGraphicsView(Dialog)
        self.land_10.setGeometry(QtCore.QRect(200, 60, 100, 100))
        self.land_10.setObjectName("land_10")
        self.land_13 = QtWidgets.QGraphicsView(Dialog)
        self.land_13.setGeometry(QtCore.QRect(500, 60, 100, 100))
        self.land_13.setObjectName("land_13")
        self.land_11 = QtWidgets.QGraphicsView(Dialog)
        self.land_11.setGeometry(QtCore.QRect(300, 60, 100, 100))
        self.land_11.setObjectName("land_11")
        self.land_12 = QtWidgets.QGraphicsView(Dialog)
        self.land_12.setGeometry(QtCore.QRect(400, 60, 100, 100))
        self.land_12.setObjectName("land_12")
        self.land_08 = QtWidgets.QGraphicsView(Dialog)
        self.land_08.setGeometry(QtCore.QRect(100, 160, 100, 100))
        self.land_08.setObjectName("land_08")
        self.land_07 = QtWidgets.QGraphicsView(Dialog)
        self.land_07.setGeometry(QtCore.QRect(100, 260, 100, 100))
        self.land_07.setObjectName("land_07")
        self.land_06 = QtWidgets.QGraphicsView(Dialog)
        self.land_06.setGeometry(QtCore.QRect(100, 360, 100, 100))
        self.land_06.setObjectName("land_06")
        self.land_05 = QtWidgets.QGraphicsView(Dialog)
        self.land_05.setGeometry(QtCore.QRect(100, 460, 100, 100))
        self.land_05.setObjectName("land_05")
        self.land_03 = QtWidgets.QGraphicsView(Dialog)
        self.land_03.setGeometry(QtCore.QRect(300, 460, 100, 100))
        self.land_03.setObjectName("land_03")
        self.land_04 = QtWidgets.QGraphicsView(Dialog)
        self.land_04.setGeometry(QtCore.QRect(200, 460, 100, 100))
        self.land_04.setObjectName("land_04")
        self.land_02 = QtWidgets.QGraphicsView(Dialog)
        self.land_02.setGeometry(QtCore.QRect(400, 460, 100, 100))
        self.land_02.setObjectName("land_02")
        self.land_01 = QtWidgets.QGraphicsView(Dialog)
        self.land_01.setGeometry(QtCore.QRect(500, 460, 100, 100))
        self.land_01.setObjectName("land_01")
        self.land_00 = QtWidgets.QGraphicsView(Dialog)
        self.land_00.setGeometry(QtCore.QRect(600, 460, 100, 100))
        self.land_00.setObjectName("land_00")
        self.land_14 = QtWidgets.QGraphicsView(Dialog)
        self.land_14.setGeometry(QtCore.QRect(600, 60, 100, 100))
        self.land_14.setObjectName("land_14")
        self.land_15 = QtWidgets.QGraphicsView(Dialog)
        self.land_15.setGeometry(QtCore.QRect(600, 160, 100, 100))
        self.land_15.setObjectName("land_15")
        self.land_17 = QtWidgets.QGraphicsView(Dialog)
        self.land_17.setGeometry(QtCore.QRect(600, 360, 100, 100))
        self.land_17.setObjectName("land_17")
        self.land_16 = QtWidgets.QGraphicsView(Dialog)
        self.land_16.setGeometry(QtCore.QRect(600, 260, 100, 100))
        self.land_16.setObjectName("land_16")
        self.player1_text = QtWidgets.QTextBrowser(Dialog)
        self.player1_text.setGeometry(QtCore.QRect(0, 650, 250, 150))
        self.player1_text.setObjectName("player1_text")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(0, 260, 90, 80))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("e:/random_dice/mymodify/_guifiles\\player1.png"))
        self.label_1.setScaledContents(False)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(700, 260, 90, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("e:/random_dice/mymodify/_guifiles\\player2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 190, 80, 80))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("e:/random_dice/mymodify/_guifiles\\../_image/dice.jpg"))
        self.label_3.setObjectName("label_3")
        self.player1 = QtWidgets.QLabel(Dialog)
        self.player1.setGeometry(QtCore.QRect(610, 470, 40, 40))
        self.player1.setText("")
        self.player1.setPixmap(QtGui.QPixmap("e:/random_dice/mymodify/_guifiles\\../_image/player1_resize.png"))
        self.player1.setScaledContents(True)
        self.player1.setObjectName("player1")
        self.player2 = QtWidgets.QLabel(Dialog)
        self.player2.setGeometry(QtCore.QRect(650, 510, 40, 40))
        self.player2.setText("")
        self.player2.setPixmap(QtGui.QPixmap("e:/random_dice/mymodify/_guifiles\\../_image/player2_resize.png"))
        self.player2.setObjectName("player2")
        self.btn2 = QtWidgets.QPushButton(Dialog)
        self.btn2.setGeometry(QtCore.QRect(420, 200, 80, 40))
        self.btn2.setObjectName("btn2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Random Dice"))
        self.btn1.setText(_translate("Dialog", "Dice_1"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">무인도!~!</p></body></html>"))
        self.btn2.setText(_translate("Dialog", "Dice_2"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
